### ISSUE TITLE
Explanation

### ISSUE THREAD

**Issue by ketaki2000** [spChalk/Fake-News-Detection#1]
Can you please provide difference between document vectors and bag of words. And need for document-vectors representation

**Comment by spChalk** [comment]
## **Bag of Words**
The Bag-of-words model is an orderless document representation — only the counts of words matter.

For a given document, you extract **only the unigram words** (aka terms) to create an unordered list of words, in order to represent the document. 

For instance, in the above example "John likes to watch movies. Mary likes movies too", the bag-of-words representation will not reveal that the verb "likes" always follows a person's name in this text.

## **Document Vectors**
Given the bag of words that you extracted from the document, you create a feature vector for the document, where each feature is a word (term) and the feature's value is a term weight. The entire document is thus a feature vector, and each feature vector corresponds to a point in a vector space.

## **Why bother with Document-Vectors?**
* Pretrained word embeddings (such as GloVe wiki gigaword used in this project) capture the semantic and syntactic meaning of a word as they are trained on large datasets.
* They capture sub-linear relationships in the vector space.
* GloVe does not rely just on local statistics (local context information of words), but incorporates global statistics (word co-occurrence) to obtain word vectors.
